"""cria tabelas microbacias, modelos, analises

Revision ID: 9087658381f4
Revises: 
Create Date: 2026-09-11 20:39:04.313556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9087658381f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microbacias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('versao')
    )
    op.create_table('analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microbacia_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PROCESSANDO', 'CONCLUIDA', 'ERRO', name='statusanalise'), nullable=False),
    sa.Column('caminho_mosaico_resultado', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mensagem_erro', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['microbacia_id'], ['microbacias.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analises')
    op.drop_table('modelos')
    op.drop_table('microbacias')
    # ### end Alembic commands ###
